### ISSUE TITLE
Add full hugo source

### ISSUE THREAD

**Issue by philipithomas** [SamuelDebruyn/hugo-material-lite#4]
Thanks for posting this theme. Can you post the full source for [materialexample.sa.muel.be](http://materialexample.sa.muel.be/), perhaps in a separate repo? It would make it much easier to debug.

**Comment by SamuelDebruyn** [comment]
Hi @philipithomas, it's already available at https://github.com/SamuelDebruyn/hugo-theme-example :)

**Comment by philipithomas** [comment]
:+1:
