### ISSUE TITLE
Switching to "dashboard" template from MDL.io

### ISSUE THREAD

**Issue by simathur** [SamuelDebruyn/hugo-material-lite#7]
Hello, 
What would be the complexity of work required to modify this theme to use the "Dashboard" template listed half-way down this list? 
https://getmdl.io/templates/index.html

A broad description of the work required would be sufficient. 

Thanks :)
Siddharth

**Comment by SamuelDebruyn** [comment]
Hi Siddharth

I am not maintaning this repository anymore myself, but you can open a PR if you want.
It would take quite some work to create another MDL-based template.

**Comment by simathur** [comment]
Thank you, that helps :)
